version: "3"
services:
  app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/opt/app
      - reserved:/opt/app/node_modules/
    entrypoint:
      - npm
      - run
      - start-docker
    logging:
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  reserved:
